<!-- Para que funcione esto tiene que ir en app/design/frontend/base/default/template/ale_block/sampletemplate.phtml -->

<?php ?>

<h1>Hello world</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pretium vel sapien nec commodo. Phasellus efficitur luctus nisl. Duis eu dolor sit amet diam scelerisque convallis. Quisque ultricies et eros eu suscipit. Duis non euismod felis. Duis ac auctor sapien, non fringilla ex. Maecenas quis pellentesque turpis. Proin sit amet arcu sodales nisl laoreet pellentesque vitae vitae purus. Donec aliquam ipsum id metus blandit tristique. Proin commodo elit pretium, vestibulum dolor hendrerit, pretium nisi. Praesent dapibus ullamcorper odio sit amet gravida. Integer vulputate consequat massa ac ullamcorper. Ut iaculis, odio in sagittis efficitur, orci sem egestas purus, at tempor magna odio vel ex. Maecenas purus risus, eleifend nec tortor eget, placerat euismod augue. Vestibulum quis urna eget odio ultricies condimentum.

Mauris ultrices, purus id vulputate placerat, dui nisl porta ligula, sit amet auctor libero purus at neque. Praesent a sagittis urna. Proin ut erat id elit posuere efficitur ac quis justo. Suspendisse semper porta condimentum. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed vitae pharetra arcu. Quisque sed felis leo. Donec sed justo et lacus vestibulum finibus nec quis elit. Pellentesque non eros metus. Morbi et ligula lobortis, malesuada leo vel, auctor velit. Nulla lectus arcu, elementum nec sem eget, venenatis accumsan tortor.
</p>
